#LOG
logging.level.es.ucm.pacv=info





# Datasource desarrollo compartido
# ATENCIÓN: a veces utilizo pacv2i para perseguir errores que me han comentado en integración
spring.datasource.url=jdbc:mysql://localhost:3306/backingtracks?useUnicode=yes&characterEncoding=UTF-8&serverTimezone=Europe/Madrid

spring.datasource.username=root
spring.datasource.password=banet1969
spring.jpa.properties.hibernate.default_schema=backingtracks
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQL8Dialect
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true
#spring.jpa.properties.hibernate.generate_statistics=true
logging.level.org.hibernate.SQL=INFO
#logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE



#Salida json algo más decente
spring.jackson.serialization.indent-output=true





